// <auto-generated />
using System;
using MgFinanceiro.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MgFinanceiro.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250826153218_SeedingData")]
    partial class SeedingData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MgFinanceiro.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            DataCriacao = new DateTime(2025, 8, 26, 15, 32, 18, 513, DateTimeKind.Utc).AddTicks(4169),
                            Nome = "Vendas de Produtos",
                            Tipo = 1
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            DataCriacao = new DateTime(2025, 8, 26, 15, 32, 18, 513, DateTimeKind.Utc).AddTicks(4238),
                            Nome = "Prestação de Serviços",
                            Tipo = 1
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            DataCriacao = new DateTime(2025, 8, 26, 15, 32, 18, 513, DateTimeKind.Utc).AddTicks(4239),
                            Nome = "Juros e Rendimentos Financeiros",
                            Tipo = 1
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            DataCriacao = new DateTime(2025, 8, 26, 15, 32, 18, 513, DateTimeKind.Utc).AddTicks(4241),
                            Nome = "Outras Receitas Operacionais",
                            Tipo = 1
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            DataCriacao = new DateTime(2025, 8, 26, 15, 32, 18, 513, DateTimeKind.Utc).AddTicks(4242),
                            Nome = "Salários e Encargos",
                            Tipo = 2
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            DataCriacao = new DateTime(2025, 8, 26, 15, 32, 18, 513, DateTimeKind.Utc).AddTicks(4243),
                            Nome = "Aluguel e Manutenção Predial",
                            Tipo = 2
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            DataCriacao = new DateTime(2025, 8, 26, 15, 32, 18, 513, DateTimeKind.Utc).AddTicks(4244),
                            Nome = "Compras de Mercadorias",
                            Tipo = 2
                        },
                        new
                        {
                            Id = 8,
                            Ativo = true,
                            DataCriacao = new DateTime(2025, 8, 26, 15, 32, 18, 513, DateTimeKind.Utc).AddTicks(4245),
                            Nome = "Impostos e Taxas",
                            Tipo = 2
                        },
                        new
                        {
                            Id = 9,
                            Ativo = true,
                            DataCriacao = new DateTime(2025, 8, 26, 15, 32, 18, 513, DateTimeKind.Utc).AddTicks(4275),
                            Nome = "Despesas com Marketing",
                            Tipo = 2
                        },
                        new
                        {
                            Id = 10,
                            Ativo = true,
                            DataCriacao = new DateTime(2025, 8, 26, 15, 32, 18, 513, DateTimeKind.Utc).AddTicks(4277),
                            Nome = "Despesas Administrativas",
                            Tipo = 2
                        });
                });

            modelBuilder.Entity("MgFinanceiro.Domain.Entities.Transacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Transacoes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Data = new DateTime(2025, 8, 21, 15, 32, 18, 513, DateTimeKind.Utc).AddTicks(7261),
                            DataCriacao = new DateTime(2025, 8, 26, 15, 32, 18, 513, DateTimeKind.Utc).AddTicks(6971),
                            Descricao = "Venda de produtos para cliente A",
                            Valor = 1500.00m
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 2,
                            Data = new DateTime(2025, 8, 23, 15, 32, 18, 513, DateTimeKind.Utc).AddTicks(7463),
                            DataCriacao = new DateTime(2025, 8, 26, 15, 32, 18, 513, DateTimeKind.Utc).AddTicks(7462),
                            Descricao = "Prestação de serviço de consultoria",
                            Valor = 800.00m
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 5,
                            Data = new DateTime(2025, 8, 16, 15, 32, 18, 513, DateTimeKind.Utc).AddTicks(7466),
                            DataCriacao = new DateTime(2025, 8, 26, 15, 32, 18, 513, DateTimeKind.Utc).AddTicks(7465),
                            Descricao = "Pagamento de salários mensais",
                            Valor = 2000.00m
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 7,
                            Data = new DateTime(2025, 8, 24, 15, 32, 18, 513, DateTimeKind.Utc).AddTicks(7468),
                            DataCriacao = new DateTime(2025, 8, 26, 15, 32, 18, 513, DateTimeKind.Utc).AddTicks(7467),
                            Descricao = "Compra de estoque",
                            Valor = 1200.00m
                        });
                });

            modelBuilder.Entity("MgFinanceiro.Domain.Entities.Transacao", b =>
                {
                    b.HasOne("MgFinanceiro.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Transacoes")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("MgFinanceiro.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
