// <auto-generated />
using System;
using MgFinanceiro.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MgFinanceiro.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250828134052_SeedDataStatic")]
    partial class SeedDataStatic
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MgFinanceiro.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nome", "Tipo")
                        .IsUnique()
                        .HasFilter("Ativo = 1");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            DataCriacao = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Vendas de Produtos",
                            Tipo = 1
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            DataCriacao = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Prestação de Serviços",
                            Tipo = 1
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            DataCriacao = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Juros e Rendimentos Financeiros",
                            Tipo = 1
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            DataCriacao = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Outras Receitas Operacionais",
                            Tipo = 1
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            DataCriacao = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Salários e Encargos",
                            Tipo = 2
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            DataCriacao = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Aluguel e Manutenção Predial",
                            Tipo = 2
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            DataCriacao = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Compras de Mercadorias",
                            Tipo = 2
                        },
                        new
                        {
                            Id = 8,
                            Ativo = true,
                            DataCriacao = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Impostos e Taxas",
                            Tipo = 2
                        },
                        new
                        {
                            Id = 9,
                            Ativo = true,
                            DataCriacao = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Despesas com Marketing",
                            Tipo = 2
                        },
                        new
                        {
                            Id = 10,
                            Ativo = true,
                            DataCriacao = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Despesas Administrativas",
                            Tipo = 2
                        });
                });

            modelBuilder.Entity("MgFinanceiro.Domain.Entities.Transacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("Data");

                    b.ToTable("Transacoes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Data = new DateTime(2025, 8, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataCriacao = new DateTime(2025, 8, 28, 13, 40, 52, 418, DateTimeKind.Utc).AddTicks(6124),
                            Descricao = "Venda de produtos para cliente A",
                            Valor = 1500.00m
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 2,
                            Data = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataCriacao = new DateTime(2025, 8, 28, 13, 40, 52, 418, DateTimeKind.Utc).AddTicks(6581),
                            Descricao = "Prestação de serviço de consultoria",
                            Valor = 800.00m
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 5,
                            Data = new DateTime(2025, 8, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataCriacao = new DateTime(2025, 8, 28, 13, 40, 52, 418, DateTimeKind.Utc).AddTicks(6583),
                            Descricao = "Pagamento de salários mensais",
                            Valor = 2000.00m
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 7,
                            Data = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataCriacao = new DateTime(2025, 8, 28, 13, 40, 52, 418, DateTimeKind.Utc).AddTicks(6584),
                            Descricao = "Compra de estoque",
                            Valor = 1200.00m
                        });
                });

            modelBuilder.Entity("MgFinanceiro.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("MgFinanceiro.Domain.Entities.Transacao", b =>
                {
                    b.HasOne("MgFinanceiro.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Transacoes")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("MgFinanceiro.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
