// <auto-generated />
using System;
using MgFinanceiro.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MgFinanceiro.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MgFinanceiro.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nome", "Tipo")
                        .IsUnique()
                        .HasFilter("Ativo = 1");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            DataCriacao = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Vendas de Produtos",
                            Tipo = 1
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            DataCriacao = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Prestação de Serviços",
                            Tipo = 1
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            DataCriacao = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Juros e Rendimentos Financeiros",
                            Tipo = 1
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            DataCriacao = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Outras Receitas Operacionais",
                            Tipo = 1
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            DataCriacao = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Salários e Encargos",
                            Tipo = 2
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            DataCriacao = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Aluguel e Manutenção Predial",
                            Tipo = 2
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            DataCriacao = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Compras de Mercadorias",
                            Tipo = 2
                        },
                        new
                        {
                            Id = 8,
                            Ativo = true,
                            DataCriacao = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Impostos e Taxas",
                            Tipo = 2
                        },
                        new
                        {
                            Id = 9,
                            Ativo = true,
                            DataCriacao = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Despesas com Marketing",
                            Tipo = 2
                        },
                        new
                        {
                            Id = 10,
                            Ativo = true,
                            DataCriacao = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Despesas Administrativas",
                            Tipo = 2
                        });
                });

            modelBuilder.Entity("MgFinanceiro.Domain.Entities.Transacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("Data");

                    b.ToTable("Transacoes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Data = new DateTime(2025, 8, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataCriacao = new DateTime(2025, 8, 28, 14, 24, 46, 444, DateTimeKind.Utc).AddTicks(1287),
                            Descricao = "Venda de produtos para cliente A",
                            Observacoes = "Venda de 50 unidades de produto X, entrega realizada em 2 dias.",
                            Valor = 1500.00m
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 2,
                            Data = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataCriacao = new DateTime(2025, 8, 28, 14, 24, 46, 444, DateTimeKind.Utc).AddTicks(1808),
                            Descricao = "Prestação de serviço de consultoria",
                            Observacoes = "Consultoria de 10 horas para otimização de processos.",
                            Valor = 800.00m
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 5,
                            Data = new DateTime(2025, 8, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataCriacao = new DateTime(2025, 8, 28, 14, 24, 46, 444, DateTimeKind.Utc).AddTicks(1811),
                            Descricao = "Pagamento de salários mensais",
                            Observacoes = "Salários de 5 funcionários, pago via transferência bancária.",
                            Valor = 2000.00m
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 7,
                            Data = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataCriacao = new DateTime(2025, 8, 28, 14, 24, 46, 444, DateTimeKind.Utc).AddTicks(1812),
                            Descricao = "Compra de estoque",
                            Observacoes = "Aquisição de 100 unidades de matéria-prima Y.",
                            Valor = 1200.00m
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 4,
                            Data = new DateTime(2025, 7, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataCriacao = new DateTime(2025, 8, 28, 14, 24, 46, 444, DateTimeKind.Utc).AddTicks(1813),
                            Descricao = "Receita de aluguel de equipamento",
                            Observacoes = "Aluguel de máquina por 5 dias para cliente externo.",
                            Valor = 600.00m
                        },
                        new
                        {
                            Id = 6,
                            CategoriaId = 6,
                            Data = new DateTime(2025, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataCriacao = new DateTime(2025, 8, 28, 14, 24, 46, 444, DateTimeKind.Utc).AddTicks(1814),
                            Descricao = "Pagamento de aluguel mensal",
                            Valor = 900.00m
                        },
                        new
                        {
                            Id = 7,
                            CategoriaId = 1,
                            Data = new DateTime(2025, 9, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataCriacao = new DateTime(2025, 8, 28, 14, 24, 46, 444, DateTimeKind.Utc).AddTicks(1815),
                            Descricao = "Venda de produtos para cliente B",
                            Observacoes = "Venda de 80 unidades de produto Z, pedido urgente.",
                            Valor = 2300.00m
                        },
                        new
                        {
                            Id = 8,
                            CategoriaId = 9,
                            Data = new DateTime(2025, 9, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataCriacao = new DateTime(2025, 8, 28, 14, 24, 46, 444, DateTimeKind.Utc).AddTicks(1817),
                            Descricao = "Campanha de marketing online",
                            Observacoes = "Anúncios no Google Ads para promoção de produto X.",
                            Valor = 500.00m
                        },
                        new
                        {
                            Id = 9,
                            CategoriaId = 3,
                            Data = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataCriacao = new DateTime(2025, 8, 28, 14, 24, 46, 444, DateTimeKind.Utc).AddTicks(1826),
                            Descricao = "Juros recebidos de aplicação",
                            Observacoes = "Juros de aplicação financeira em fundo de renda fixa.",
                            Valor = 300.00m
                        },
                        new
                        {
                            Id = 10,
                            CategoriaId = 8,
                            Data = new DateTime(2025, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataCriacao = new DateTime(2025, 8, 28, 14, 24, 46, 444, DateTimeKind.Utc).AddTicks(1827),
                            Descricao = "Pagamento de impostos municipais",
                            Valor = 400.00m
                        },
                        new
                        {
                            Id = 11,
                            CategoriaId = 6,
                            Data = new DateTime(2025, 6, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataCriacao = new DateTime(2025, 8, 28, 14, 24, 46, 444, DateTimeKind.Utc).AddTicks(1828),
                            Descricao = "Serviço de manutenção de equipamentos",
                            Observacoes = "Manutenção preventiva de 3 máquinas industriais.",
                            Valor = 700.00m
                        },
                        new
                        {
                            Id = 12,
                            CategoriaId = 1,
                            Data = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataCriacao = new DateTime(2025, 8, 28, 14, 24, 46, 444, DateTimeKind.Utc).AddTicks(1830),
                            Descricao = "Venda de produtos para cliente C",
                            Observacoes = "Venda de 60 unidades de produto Y, pagamento à vista.",
                            Valor = 1800.00m
                        },
                        new
                        {
                            Id = 13,
                            CategoriaId = 10,
                            Data = new DateTime(2025, 8, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataCriacao = new DateTime(2025, 8, 28, 14, 24, 46, 444, DateTimeKind.Utc).AddTicks(1831),
                            Descricao = "Despesas com material de escritório",
                            Observacoes = "Compra de papel, canetas e outros suprimentos.",
                            Valor = 200.00m
                        },
                        new
                        {
                            Id = 14,
                            CategoriaId = 2,
                            Data = new DateTime(2025, 9, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataCriacao = new DateTime(2025, 8, 28, 14, 24, 46, 444, DateTimeKind.Utc).AddTicks(1832),
                            Descricao = "Receita de consultoria estratégica",
                            Valor = 1200.00m
                        },
                        new
                        {
                            Id = 15,
                            CategoriaId = 7,
                            Data = new DateTime(2025, 7, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataCriacao = new DateTime(2025, 8, 28, 14, 24, 46, 444, DateTimeKind.Utc).AddTicks(1833),
                            Descricao = "Compra de matérias-primas",
                            Observacoes = "Aquisição de matéria-prima para produção de produto Z.",
                            Valor = 1500.00m
                        },
                        new
                        {
                            Id = 16,
                            CategoriaId = 8,
                            Data = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataCriacao = new DateTime(2025, 8, 28, 14, 24, 46, 444, DateTimeKind.Utc).AddTicks(1834),
                            Descricao = "Pagamento de taxas estaduais",
                            Observacoes = "ICMS referente a vendas do mês de junho.",
                            Valor = 350.00m
                        },
                        new
                        {
                            Id = 17,
                            CategoriaId = 4,
                            Data = new DateTime(2025, 8, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataCriacao = new DateTime(2025, 8, 28, 14, 24, 46, 444, DateTimeKind.Utc).AddTicks(1835),
                            Descricao = "Receita de royalties",
                            Observacoes = "Royalties de licenciamento de software proprietário.",
                            Valor = 1000.00m
                        },
                        new
                        {
                            Id = 18,
                            CategoriaId = 6,
                            Data = new DateTime(2025, 9, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataCriacao = new DateTime(2025, 8, 28, 14, 24, 46, 444, DateTimeKind.Utc).AddTicks(1837),
                            Descricao = "Manutenção de veículos da empresa",
                            Valor = 600.00m
                        },
                        new
                        {
                            Id = 19,
                            CategoriaId = 1,
                            Data = new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataCriacao = new DateTime(2025, 8, 28, 14, 24, 46, 444, DateTimeKind.Utc).AddTicks(1838),
                            Descricao = "Venda de produtos para cliente D",
                            Observacoes = "Venda de 100 unidades de produto X, entrega em 3 dias.",
                            Valor = 2500.00m
                        },
                        new
                        {
                            Id = 20,
                            CategoriaId = 10,
                            Data = new DateTime(2025, 8, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataCriacao = new DateTime(2025, 8, 28, 14, 24, 46, 444, DateTimeKind.Utc).AddTicks(1839),
                            Descricao = "Despesas com treinamento de equipe",
                            Valor = 800.00m
                        });
                });

            modelBuilder.Entity("MgFinanceiro.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataCriacao = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "teste@exemplo.com",
                            Nome = "Jose Teste",
                            SenhaHash = "$2a$11$q4yBPFxw9Wo4G9BhzeVUVeN5BvUcrkYBcf7Lvjw6FRczlu.ie2S0W"
                        });
                });

            modelBuilder.Entity("MgFinanceiro.Domain.Entities.Transacao", b =>
                {
                    b.HasOne("MgFinanceiro.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Transacoes")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("MgFinanceiro.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
